bike/urls.py
from django.urls import re_path, path
from . import views
app_name = 'bike'
urlpatterns = [
    re_path(r'^$', views.bike_list, name="bikelist"),
    re_path(r'^bikedetail/(?P<bikeid>[\w-]+)/$',
            views.bike_detail, name="bikedetail"),
    re_path(r'^bikemodelcreate/$', views.model_create, name="mcreate"),
    re_path(r'^bikemodels/$', views.bikemodels_list, name="bikemodelslist"),
    re_path(r'^bikemodels/(?P<modelid>[\w-]+)/$',
            views.bikemodel_detail, name="bikemodeldetail"),
]

celli_webapp/urls.py
from django.contrib import admin
from django.urls import include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

# Change admin site title
admin.site.site_header = "Cellibini Bikes Company WebApp Login"
admin.site.site_title = "Cellibini Bikes Company"

app_name = 'celli_webapp'


urlpatterns = [
    # path('admin/', admin.site.urls),
    # path(r'^admin/', admin.site.urls),
    
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^taskschedule/', include('taskschedule.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^customers/', include('customers.urls')),
    re_path(r'^bike/', include('bike.urls')),
    re_path(r'^masterinventory/', include('masterInventory.urls')),
    re_path(r'^about/$', views.about),
    re_path(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

masterInventory/urls.py
from django.conf.urls import url
from . import views

app_name = "masterInventory"

urlpatterns = [
	url(r'^$', views.inventory_list, name="inventorylist"),  # view all the inventory
	url(r'^inventoryorder/create$', views.inventoryorder_create, name="inventoryorder"),
	url(r'^inventoryorder/list$', views.inventoryorder_list, name="inventoryorderlist"),
	url(r'^inventoryorder/detail/(?P<orderid>[\w-]+)$', views.inventoryorder_detail, name="inventoryorderdetail"),

	url(r'^inventoryorder/approve/(?P<orderid>[\w-]+)$',views.inventoryinvoice_create, name="inventoryorderapprove"),
	#invoice routes
	url(r'^inventoryinvoice/list$', views.inventoryinvoice_list,name="inventoryinvoicelist"),
	url(r'^inventoryinvoice/detail/(?P<invoiceid>[\w-]+)$',views.inventoryinvoice_detail, name="inventoryinvoicedetail"),

	#supplier routes
	url(r'^itemcreate/$', views.inventory_item_create, name="inventoryadd"),
	url(r'^supplierlist/$', views.supplier_list, name="supplierlist"),

	#defects routes
	url(r'^defects/$', views.defects_list, name="defectslist"),
	url(r'^defects/report/(?P<invoiceid>[\w-]+)$', views.defect_create, name="defectcreate"),
	url(r'^defects/detail/(?P<defectinvoiceid>[\w-]+)/$', views.defect_detail, name="defectdetail"),
	# url(r'^defects/reportdefect$', views.create_defect, name="createdefect"),


]

masterInventory/models.py
from django.db import models
from decimal import Decimal


# Create your models here.
class MasterInventory(models.Model):
	class Meta:
		db_table = "tblMasterInventory"
		
	mi_inventoryid = models.AutoField(primary_key=True)
	#partid = 
	mi_partname = models.CharField(max_length=100)
	mi_numberofstocks = models.IntegerField()
	mi_parlevel = models.IntegerField()
	mi_price = models.DecimalField(max_digits=7, decimal_places=2, default=Decimal('00000.00'))


	def __str__(self):
		return str(self.mi_partname)

	def updatestock(self, received):
		self.mi_numberofstocks += received
		self.save()

#only admin can add a new supplier
class Supplier(models.Model):
	class Meta:
		db_table = "tblSupplier"

	s_supplierid = models.AutoField(primary_key=True)
	s_suppliername = models.CharField(max_length=30)
	s_companyname = models.CharField(max_length=100, blank=True, null=True,default="")
	s_contractstartdate = models.DateTimeField()
	s_is_active = models.BooleanField(default=True)
	s_phone =  models.CharField(max_length=16)
	s_email = models.CharField(max_length=30)

	def __str__(self):
		return str(self.s_companyname)

class SupplierOrder(models.Model):
	class Meta:
		db_table = "tblSupplierOrder"

	so_supplierordernumber = models.AutoField(primary_key=True)
	so_supplierid = models.ForeignKey(Supplier, on_delete=models.PROTECT)
	so_date = models.DateTimeField(auto_now_add=True)
	so_isreceived = models.BooleanField(default=False)

	def orderreceived(self):
		self.so_isreceived = True
		self.save()

class SupplierOrderLineItem(models.Model):
	class Meta:
		db_table = "jncSupplierOrderLineItem"

	soli_supplierordernumber = models.ForeignKey(SupplierOrder, on_delete=models.PROTECT)
	soli_inventoryid = models.ForeignKey(MasterInventory,on_delete=models.PROTECT)
	soli_quantity = models.IntegerField()

class SupplierInvoice(models.Model):
	class Meta:
		db_table = "tblSupplierInvoice"

	si_supplierinvoiceid = models.AutoField(primary_key=True)	
	si_supplierinvoicenumber = models.CharField(max_length=16)
	si_ordernumber = models.ForeignKey(SupplierOrder, on_delete=models.PROTECT)
	si_date = models.DateTimeField()
	si_hst = models.DecimalField(max_digits=3, decimal_places=2, default=Decimal('0.13'))

	def __str__(self):
		return str(self.si_supplierinvoiceid)

	def received(self):
		self.si_ordernumber.orderreceived()

class SupplierInvoiceLineItem(models.Model):
	class Meta:
		db_table = "jncSupplierInvoiceLineItem"

	sili_supplierinvoicenumber = models.ForeignKey(SupplierInvoice, on_delete=models.PROTECT)
	sili_inventoryid = models.ForeignKey(MasterInventory,on_delete=models.PROTECT)
	sili_quantityshipped = models.IntegerField(default=0)
	sili_price = models.DecimalField(max_digits=8, decimal_places=2)  # 999999.99

	def updatestock(self):
		inventory = MasterInventory.objects.get(mi_inventoryid = str(self.sili_inventoryid.mi_inventoryid))
		inventory.updatestock(self.sili_quantityshipped)


	def calculateprice(self):
		inventory = MasterInventory.objects.get(mi_inventoryid = str(self.sili_inventoryid.mi_inventoryid))
		self.sili_price = inventory.mi_price * self.sili_quantityshipped	

class Defect(models.Model):
    class Meta:
        db_table = "tblDefect"
    
    d_defectid = models.AutoField(primary_key=True)
    d_supplierinvoicenumber = models.ForeignKey(SupplierInvoice, on_delete=models.PROTECT)
    d_inventoryid = models.ForeignKey(MasterInventory,on_delete=models.PROTECT)
    d_employeeid = models.ForeignKey(
    	'accounts.Employee', on_delete=models.PROTECT)
    d_quantity = models.IntegerField(default=0)
    d_date = models.DateTimeField(auto_now_add=True)
    d_defectdesc = models.CharField(max_length=200, default="")

    def updatestock(self):
    	inventory = MasterInventory.objects.get(mi_inventoryid = str(self.d_inventoryid.mi_inventoryid))
    	inventory.updatestock(-self.d_quantity)

masterInventory/forms.py
from django import forms
from django.forms import modelformset_factory
from . import models


class CreateInventoryItem(forms.ModelForm):
	class Meta:
		model = models.MasterInventory
		fields = ['mi_partname', 'mi_numberofstocks', 'mi_parlevel']
		#add restrictions for input later


class CreateInventoryOrder(forms.ModelForm):
	class Meta:
		model = models.SupplierOrder
		fields = ['so_supplierid']


InventoryItemFormset = modelformset_factory(
	models.SupplierOrderLineItem, fields=('soli_inventoryid', 'soli_quantity',))


class CreateOrderLineItem(forms.ModelForm):
	class Meta:
		model = models.SupplierOrderLineItem
		fields = ['soli_quantity']
		# labels = {
  #                   'soli_quantity': nameofPart
		# }
		widgets = {'soli_quantity': forms.IntegerField()}


class CreateInventoryInvoice(forms.ModelForm):
	class Meta:
		model = models.SupplierInvoice
		fields = ['si_supplierinvoicenumber']
		labels ={'si_supplierinvoicenumber':'Supplier Invoice Number'}

class ReportDefects(forms.ModelForm):
	class Meta:
		model = models.Defect
		fields = ['d_quantity', 'd_defectdesc']
		labels= {
		'd_quantity':'Quantity',
		'd_defectdesc':'description'
		}
		widgets = {
		'd_defectdesc': forms.Textarea(attrs={"rows":5, "cols":20})
		}

masterInventory/views.py
from django.shortcuts import render, redirect
from .models import *
from . import forms
from django import forms as dforms
from django.db.models import Sum
from django.forms import modelformset_factory, formset_factory
import json
from decimal import *
from django.utils import timezone
from .render import Render
from django.views.generic import View
from datetime import datetime
from accounts.models import Employee
from django.contrib.auth.models import User

def inventory_list(request):
	inventories = MasterInventory.objects.all().order_by('mi_inventoryid')
	return render(request, 'masterinventory/inventory_list.html', {'inventories':inventories})

#only super user and sales should have access to this
def inventory_item_create(request):
	if request.method =='POST':
		form = forms.CreateQuote(request.POST)
		if form.is_valid():
			#save article to db
			instance = form.save(commit=False)
			instance.save()
			return redirect('masterInventory:inventorylist')
	else:
		form = forms.CreateInventoryItem()

	return render(request, 'masterinventory/inventory_create.html', {'form': form})

#----
#ORDERINVENTORY VIEWS
#----
def inventoryorder_create(request):
	inventories = MasterInventory.objects.all().order_by('mi_inventoryid')
	numberofinventory = MasterInventory.objects.all().count()
	partform = []
	for inventory in inventories:
		partname = {"name":inventory.mi_partname, "par":inventory.mi_parlevel, "onhand":inventory.mi_numberofstocks}
		partform.append(partname)
	if request.method == 'POST':
		io_form = forms.CreateInventoryOrder(request.POST)
		if io_form.is_valid():
			instance = io_form.save(commit=False)
			instance.save()

			inventoriesitems = list(MasterInventory.objects.values_list('mi_inventoryid', flat=True))
			print(request.POST.getlist('orderitem'))

			orderitem = dict(zip(inventoriesitems, request.POST.getlist('orderitem')))
			for key, quantity in orderitem.items():
				if int(quantity) > 0:
					so_object = SupplierOrderLineItem()
					so_object.soli_supplierordernumber = instance
					so_object.soli_inventoryid = MasterInventory.objects.get(mi_inventoryid=key)
					so_object.soli_quantity = int(quantity)
					so_object.save()

			return redirect('masterInventory:inventoryorderlist')

	else:
		

		io_form = forms.CreateInventoryOrder()


	return render(request, 'inventoryorder/inventoryorder_create.html', {'io_form':io_form, 'partform':partform, 'inventories':inventories})

def inventoryorder_list(request):
	orders = SupplierOrder.objects.filter(so_isreceived=False).order_by('-so_date')
	return render(request, 'inventoryorder/inventoryorder_list.html', {'orders':orders})


def inventoryorder_detail(request, orderid):
	order = SupplierOrder.objects.get(so_supplierordernumber=orderid)
	orderitems = SupplierOrderLineItem.objects.filter(soli_supplierordernumber=orderid)
	return render(request, 'inventoryorder/inventoryorder_detail.html', {'order':order, 'orderitems':orderitems})


#----
#ORDERINVOICE VIEWS
#----
#recieve or approved that an inventory order has been received 
def inventoryinvoice_create(request, orderid):
	order = SupplierOrder.objects.get(so_supplierordernumber=orderid)
	orderitems = SupplierOrderLineItem.objects.filter(soli_supplierordernumber=orderid)

	partform = []
	for orderitem in orderitems:
		partname = {"inventoryid":orderitem.soli_inventoryid.mi_inventoryid,"name":orderitem.soli_inventoryid.mi_partname, "ordered":orderitem.soli_quantity}
		partform.append(partname)


	if request.method == 'POST':
		invoice_form = forms.CreateInventoryInvoice(request.POST)
		print(invoice_form.is_valid())
		if invoice_form.is_valid():
			instance = invoice_form.save(commit=False)
			instance.si_ordernumber = order
			instance.si_date = datetime.now()
			instance.save()

			inventoriesitems = list(SupplierOrderLineItem.objects.filter(soli_supplierordernumber=instance.si_ordernumber).values_list('soli_inventoryid_id', flat=True))

			orderitem = dict(zip(inventoriesitems, request.POST.getlist('orderitem')))
			for key, quantity in orderitem.items():
				inventoryitem = MasterInventory.objects.get(mi_inventoryid=key)
				sili_object = SupplierInvoiceLineItem(sili_supplierinvoicenumber=instance, sili_inventoryid=inventoryitem, sili_quantityshipped=int(quantity))
				sili_object.calculateprice()
				sili_object.save()
				sili_object.updatestock()

			return redirect('masterInventory:inventoryinvoicelist')

	else:
		invoice_form = forms.CreateInventoryInvoice()

	return render(request, 'inventoryinvoice/inventoryinvoice_create.html', {'order':order, 'invoice_form':invoice_form, 'partform':partform})

def inventoryinvoice_list(request):
	orders = SupplierInvoice.objects.all().order_by('si_date')
	return render(request, 'inventoryinvoice/inventoryinvoice_list.html', {'orders':orders})

def inventoryinvoice_detail(request, invoiceid):
	order = SupplierInvoice.objects.get(si_supplierinvoiceid=invoiceid) #its actually invoice number
	orderitems = SupplierInvoiceLineItem.objects.filter(sili_supplierinvoicenumber=order.si_supplierinvoiceid)
	subtotal = 0
	for item in orderitems:
		 subtotal += Decimal(item.sili_quantityshipped) * item.sili_price

	total = (Decimal(1) + order.si_hst) * subtotal
	total = "{:.2f}".format(total)
	
	return render(request, 'inventoryinvoice/inventoryinvoice_detail.html', {'order':order, 'orderitems':orderitems,'subtotal':subtotal, 'total':total})

#----
#SUPPLIER VIEWS
#----
def supplier_list(request):
	suppliers = Supplier.objects.filter(s_is_active=1)
	return render(request, 'supplier/supplier_list.html', {'suppliers':suppliers})

#----
#DEFECTS VIEWS
#----

def defects_list(request):
	defects = Defect.objects.values('d_supplierinvoicenumber__si_supplierinvoicenumber').annotate(totalquantity=Sum('d_quantity'))
	return render(request, 'defect/defects_list.html', {'defects':defects})

def defect_detail(request, defectinvoiceid):
	invoice = SupplierInvoice.objects.get(si_supplierinvoicenumber=defectinvoiceid)
	defects = Defect.objects.filter(d_supplierinvoicenumber=invoice)
	return render(request, 'defect/defects_detail.html', {'defects':defects,'defectinvoiceid':defectinvoiceid})

def defect_create(request, invoiceid):
	invoice = SupplierInvoice.objects.get(si_supplierinvoiceid=invoiceid)
	receiveditems = SupplierInvoiceLineItem.objects.filter(sili_supplierinvoicenumber=invoice)
	partselection = []
	print(request.user.id)

	for receiveditem in receiveditems:
		partname = {"id":receiveditem.sili_inventoryid.mi_inventoryid, "name":receiveditem.sili_inventoryid.mi_partname}
		partselection.append(partname)

	if request.method == 'POST':
		defect_form = forms.ReportDefects(request.POST)
		if (defect_form.is_valid()):
			instance = defect_form.save(commit=False)
			instance.d_inventoryid = MasterInventory.objects.get(mi_inventoryid=request.POST['part'])
			instance.d_supplierinvoicenumber = invoice
			instance.d_employeeid = Employee.objects.get(e_userid=request.user.id)   
			instance.d_date = datetime.now()
			instance.save()
			instance.updatestock()
			return redirect('masterInventory:defectslist')
	else:
		defect_form = forms.ReportDefects()

	return render(request, 'defect/defects_create.html', {'defect_form':defect_form, 'invoice':invoice, 'partselection':partselection})

#REPORT VIEWS

class Pdfinventory(View):

    def get(self, request):
        today = timezone.now()
        inventories = MasterInventory.objects.all().order_by('mi_inventoryid')
        return Render.render('masterinventory/inventory_report.html', {'today':today, 'inventories':inventories})

class Pdforder(View):

    def get(self, request, orderid):
        order = SupplierOrder.objects.get(so_supplierordernumber=orderid)
        orderitems = SupplierOrderLineItem.objects.filter(soli_supplierordernumber=orderid)
        return Render.render('masterinventory/inventory_report.html', {'order':order, 'orderitems':orderitems})

masterInventory/templates/inventoryinvoice/inventoryinvoice_create.html
{% extends 'base-layout.html' %}
{% block content %}
<br>
<br>
<br>
    <div class="Order_detail">
        <h1>Order Invoice Approval</h1>
        <h2>Order # {{ order.so_supplierordernumber }}</h2>
        <h3>Supplier Name: {{ order.so_supplierid }}</h3>
        <h3>Date Ordered: {{ order.so_date }}</h3>
        <form class="" action="{% url 'masterInventory:inventoryorderapprove' orderid=order.so_supplierordernumber %}" method="post"
            enctype="multipart/form-data">
            {% csrf_token %}
            {{ invoice_form }}
            <div class="inventory">
                <table class="table table-hover table-sm table-bordered mx-auto" style="width: 1000px;">
                    <tr align="center">
                        <th>Part ID</th>
                        <th>Part Name</th>
                        <th>Ordered</th>
                        <th>Received</th>
                    </tr>
                    {% for part in partform %}
                        <tr>
                            <td>{{part.inventoryid}}</td>
                            <td>{{part.name }}</td>
                            <td>{{part.ordered }}</td>
                            <td><input type="number" id="{{ part.inventoryid }}" name="orderitem" value="{{part.ordered}}"></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <input type="submit" value="Create">
        </form>
    </div>
    {% endblock %}

masterInventory/templates/inventoryinvoice/inventoryinvoice_detail.html
{% extends 'base-layout.html' %}
{% block content %}
<br>
<br>
<br>
    <div class="Order_detail">
        <h1>Order Invoice</h1>
        <h2> invoice # {{ order.si_supplierinvoicenumber }}</h2>
        <h3>Supplier Name: {{ order.so_supplierid }}</h3>
        <h3>Date Ordered: {{ order.si_date }}</h3>
            <div class="inventory">
                <table border="1">
                    <tr align="center">
                        <th>Part ID</th>
                        <th>Part Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                    {% for item in orderitems %}
                        <tr>
                            <td>{{item.sili_inventoryid.mi_inventoryid }}</td>
                            <td>{{item.sili_inventoryid.mi_partname }}</td>
                            <td>{{item.sili_quantityshipped }}</td>
                            <td>{{item.sili_price}}</td>
                        </tr>
                    {% endfor %}
                </table>
    </div>
    <h3>Subtotal: ${{subtotal}}(CAD)</h3>
    <h2>Total: ${{   total }}(CAD)</h2>
                <div class="col-3">
                        <a href="{% url 'masterInventory:defectcreate' invoiceid=order.si_supplierinvoiceid %}"><button type="submit" class="btn btn-success">Report Defect</button></a>
                    </div>   
{% endblock %}

masterInventory/templates/inventoryinvoice/inventoryinvoice_list.html
{% extends 'base-layout.html' %}

{% block content%}<br /><br /><br />
<h1 class="text-center text-info">Cellibini Bikes Inventory Invoice List History</h1>
<div class="Order List">
	<table class="table table-hover table-sm table-bordered mx-auto" style="width: 1000px;">
		<tr>
			<th>Invoice number</th>
			<th>Date</th>
		</tr>
	
	{% for order in orders %}
	<div class="inventory">
		<tr align="center">
			<td><a href="{% url 'masterInventory:inventoryinvoicedetail' invoiceid=order.si_supplierinvoiceid %}">{{order.si_supplierinvoicenumber}}</td>
			<td>{{order.si_date}}</td>
		</tr>
	</div>
	{% endfor %}
</table>
</div>
{% endblock %}

masterInventory/templates/inventoryinvoice/inventoryinvoice_report.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Inventory Report</title>
        <style type="text/css">
        @page {
        size: A4;
        margin: 1cm;
        }
        .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
        }
        .table th,
        .table td {
        padding: 5px;
        vertical-align: top;
        border-top: 1px solid #000;
        text-align: center;
        }
        .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
        }
        .table tbody + tbody {
        border-top: 2px solid #000;
        }
        .table .table {
        background-color: #fff;
        }
        .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
        }
        .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
        }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h3>Inventory Report - {{ today | date:"d/m/Y" }}</h3>
                </div>
                <div class="list-group">
                    <p>Name: {{ request.user.first_name }} {{ request.user.last_name }}</p>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <tr>
                                <th>Inventory ID</th>
                                <th>Part Name</th>
                                <th>Stocks on Hand</th>
                                <th>PAR Level</th>
                            </tr>
                        </tr>
                    </thead>
                    <tbody>
                        {% for inventory in inventories %}
                            <tr>
                                <td>{{inventory.mi_inventoryid}}</td>
                                <td>{{inventory.mi_partname}}</td>
                                <td>{{inventory.mi_parlevel}}</td>
                                <td>{{inventory.mi_numberofstocks}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>