accounts/urls.py
from django.urls import re_path, path
from . import views
from django.contrib import admin


app_name = 'accounts'

urlpatterns = [
    path('pdf/apprentices', views.Pdfapprentices.as_view()),
    # re_path(r'^signup/$', views.signup_view, name='signup'),
    re_path(r'^login/$', views.login_view, name="login"),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^profile/', views.profile, name='profile'),
    re_path(r'^password/$', views.change_password, name='change_password'),
    re_path(r'^employeecreate/$', views.employee_create, name="ecreate"),
    re_path(r'^customercreate/$', views.customer_create, name="ccreate"),
    re_path(r'^customers/$', views.customer_list, name='clist'),
    re_path(r'^employees/$', views.employee_list, name='elist'),
    re_path(r'^customerdetail/(?P<customerid>[\w-]+)$',
            views.customer_detail, name="customerdetail"),
    
]

bike/urls.py
from django.urls import re_path, path
from . import views
app_name = 'bike'
urlpatterns = [
    re_path(r'^$', views.bike_list, name="bikelist"),
    re_path(r'^bikedetail/(?P<bikeid>[\w-]+)/$',
            views.bike_detail, name="bikedetail"),
    re_path(r'^bikemodelcreate/$', views.model_create, name="mcreate"),
    re_path(r'^bikemodels/$', views.bikemodels_list, name="bikemodelslist"),
    re_path(r'^bikemodels/(?P<modelid>[\w-]+)/$',
            views.bikemodel_detail, name="bikemodeldetail"),
]

celli_webapp/urls.py
from django.contrib import admin
from django.urls import include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

# Change admin site title
admin.site.site_header = "Cellibini Bikes Company WebApp Login"
admin.site.site_title = "Cellibini Bikes Company"

app_name = 'celli_webapp'


urlpatterns = [
    # path('admin/', admin.site.urls),
    # path(r'^admin/', admin.site.urls),
    
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^taskschedule/', include('taskschedule.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^customers/', include('customers.urls')),
    re_path(r'^bike/', include('bike.urls')),
    re_path(r'^masterinventory/', include('masterInventory.urls')),
    re_path(r'^about/$', views.about),
    re_path(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.


class Employee(models.Model):
    class Meta:
        db_table = "tblEmployee"

    e_userid = models.OneToOneField(User, primary_key=True, on_delete=models.PROTECT)
    e_streetaddress1 = models.CharField(blank=False, max_length=100)
    e_streetaddress2 = models.CharField(blank=True, max_length=100)
    e_city = models.CharField(blank=False, max_length=100)
    e_province = models.CharField(blank=False, max_length=100)
    e_postalcode = models.CharField(blank=False, max_length=6)
    e_country = models.CharField(blank=False, default='CA', max_length=100)
    e_phonenumber = models.CharField(blank=False, max_length=15)
    e_salary = models.DecimalField(decimal_places=2, max_digits=10)
    e_startdate = models.DateField(null=False)
    # e_stoptdate = models.DateField(blank=True, default='', null=True)
    e_sinnumber = models.CharField(max_length=9)
    e_isapprentice = models.BooleanField(default=False)

    # def get_queryset(self):
    #     return super(Employee, self).get_queryset().filter(isapprentice = True)

    def __str__(self):
        return str(self.e_userid.username)
    
    def firstname(self):
        return str(self.e_userid.first_name)

    def lastname(self):
        return str(self.e_userid.last_name)
    
    def formatted_salary(self):
        return '%.2f CAD' % self.e_salary
    
        

class Customer(models.Model):
    class Meta:
        db_table = "tblCustomer"

    c_customerid = models.AutoField(primary_key=True)
    c_userid = models.OneToOneField(User, on_delete=models.PROTECT)
    c_streetaddress1 = models.CharField(blank=False, max_length=100)
    c_streetaddress2 = models.CharField(blank=True, max_length=100)
    c_city = models.CharField(blank=False, max_length=100)
    c_province = models.CharField(blank=False, max_length=100)
    c_postalcode = models.CharField(blank=False, max_length=6)
    c_country = models.CharField(blank=False, default='CA', max_length=100)
    c_phonenumber = models.CharField(blank=False, max_length=15)
    c_dateregistered = models.DateTimeField(auto_now_add=True)
    c_issubscribed = models.BooleanField(default=True)
    c_companyname = models.CharField(blank=True, max_length=150)
    c_isactive = models.BooleanField(default=True)

    def __str__(self):
        return str(self.c_customerid)
    
    def firstname(self):
        return str(self.c_userid.first_name)
    
    def lastname(self):
        return str(self.c_userid.last_name)
    
    def email(self):
        return str.lower(self.c_userid.email)
    
    
    
    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . import models
from .models import Employee, Customer
from django.forms import modelformset_factory


class DefaultUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email',
                  'first_name', 'last_name',
                  'password1', 'password2')

    def save(self, commit=True):
        user = super(DefaultUserForm, self).save(commit=False)
        user.is_staff = True
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class CreateEmployeeAccountForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['e_streetaddress1', 'e_streetaddress2', 'e_city', 'e_province', 'e_postalcode',
                  'e_country', 'e_phonenumber', 'e_salary', 'e_startdate', 'e_sinnumber', 'e_isapprentice'
                  ]
        labels = {
            'e_streetaddress1': 'Street Address1',
            'e_streetaddress2': 'Street Address2',
            'e_city': 'City',
            'e_province': 'Province',
            'e_postalcode': 'Postal Code',
            'e_country': 'Country',
            'e_phonenumber': 'Phone Number',
            'e_salary': 'Salary',
            'e_startdate': 'Start Date',
            'e_sinnumber': 'SIN Number',
            'e_isapprentice': 'Is Apprentice',
        }


class CustomerUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email',
                  'first_name', 'last_name')
        labels = {
            'username': 'User Name',
            'email': 'Email Address',
            'first_name': 'Email Address',
            'last_name': 'Last Name',
        }

    def save(self, commit=True):
        user = super(CustomerUserForm, self).save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class CreateCustomerAccountForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['c_streetaddress1', 'c_streetaddress2', 'c_city', 'c_province', 'c_postalcode',
                  'c_country', 'c_phonenumber', 'c_issubscribed', 'c_companyname'
                  ]
        labels = {
            'c_streetaddress1': 'Street Address1',
            'c_streetaddress2': 'Street Address2',
            'c_city': 'City',
            'c_province': 'Province',
            'c_postalcode': 'Postal Code',
            'c_country': 'Country',
            'c_phonenumber': 'Phone Number',
            'c_issubscribed': 'Is Subscrbed User',
            'c_companyname': 'Company Name'
        }

accounts/views.py
from . import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import Employee, Customer
from django.contrib.auth.models import User
from .forms import DefaultUserForm, CustomerUserForm, CreateEmployeeAccountForm, CreateCustomerAccountForm
from .render import Render
from django.utils import timezone
from django.views.generic import View




# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('tasks:list')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })


@login_required(login_url='/accounts/login/')
def profile(request):
    employee = Employee.objects.get(e_userid=request.user.id)
    print(request.user.id)
    args = {'user':request.user, 'employee':employee}
    return render(request, 'accounts/profile.html', {'args': args})
    

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        messages.info(request, "Logged out successfully!")
        return redirect('accounts:login')

@login_required(login_url='/accounts/login/')
def employee_create(request):
    if request.method == 'POST':
        form = DefaultUserForm(request.POST or None)
        create_employee = CreateEmployeeAccountForm(request.POST or None)

        if form.is_valid() and create_employee.is_valid():
            request.user.is_staff = True
            user = form.save()
            newemployee = create_employee.save(commit=False)
            newemployee.e_userid = user
            newemployee.save()
            return redirect('tasks:list')
    else:
        form = DefaultUserForm()
        create_employee = CreateEmployeeAccountForm()
    return render(request, 'accounts/employee_create.html', {'form': form, 'create_employee': create_employee})


@login_required(login_url='/accounts/login/')
def customer_create(request):
    if request.method == 'POST':
        form = CustomerUserForm(request.POST or None)
        create_customer = CreateCustomerAccountForm(request.POST or None)

        if form.is_valid() and create_customer.is_valid():
            user = form.save()
            newcustomer = create_customer.save(commit=False)
            newcustomer.c_userid = user
            newcustomer.save()
            return redirect('accounts:clist')
    else:
        form = CustomerUserForm()
        create_customer = CreateCustomerAccountForm()
    return render(request, 'accounts/customer_create.html', {'form': form, 'create_customer': create_customer})


def customer_list(request):
    customers = Customer.objects.all()
    return render(request, 'accounts/customer_list.html', {'customers': customers})


def employee_list(request):
    employees = Employee.objects.all()
    return render(request, 'accounts/employee_list.html', {'employees': employees})


def customer_detail(request, customerid):
    customer = Customer.objects.get(c_customerid = customerid)
    return render(request, 'accounts/customer_detail.html', {'customer': customer})
    
# http://127.0.0.1:8000/accounts/pdf/apprentices
class Pdfapprentices(View):

    def get(self, request):
        today = timezone.now()
        apprentices = Employee.objects.all().filter(e_isapprentice=True)
        return Render.render('accounts/apprentices_report.html', {'today': today, 'apprentices': apprentices, 'user':request.user})












# ----------------------------------------------------------------------------
# No Need with This
# Don't Remove this
# ----------------------------------------------------------------------------
# def signup_view(request):
#     if request.method == 'POST':
#         signupForm = UserCreationForm(request.POST)
#         if signupForm.is_valid():
#             user = signupForm.save()
#             # log the user in
#             login(request, user)
#             return redirect('customers:homepage')
#     else:
#         signupForm = UserCreationForm()
#     return render(request, 'accounts/signup.html', {'form': signupForm})

accounts/templates/accounts/apprentices_report.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Apprentices Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody+tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Apprentices Report - {{ today | date:"d/m/Y" }}</h3>
            </div>
            <div class="list-group">
                <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
            </div>
            <table class="table">
                <thead>
                    <tr>
                    <tr>
                        <th>Employee ID</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Joined Date</th>
                        <th>Salary</th>
                    </tr>
                    </tr>
                </thead>
                <tbody>
                    {% for apprentice in apprentices %}
                    <div class="apprentice-list">
                        <tr>
                            <td>{{apprentice.e_userid.id}}</td>
                            <td>{{ apprentice.firstname }} {{ apprentice.lastname }}</td>
                            <td>{{ apprentice.e_streetaddress1 }} {{ apprentice.e_streetaddress2 }},
                                {{ apprentice.e_city }} {{ apprentice.e_province }} - {{ apprentice.e_postalcode }}
                                {{ apprentice.e_country }}</td>
                            <td>{{ apprentice.e_startdate }}</td>
                            <td>$ {{ apprentice.formatted_salary }}</td>
                            {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>

</html>

accounts/templates/accounts/change_password.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<br />
<br />
<br />

<div class="card">
    <div class="card-body">
        <h4 class="card-title"> Change your password</h4>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}<button type="submit" class="btn btn-success">Change password </button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/customer_create.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="'row">
        {% block content %}
        <br />
        <br />
        <br />
        <h1 class="text-center text-info">Add Customer</h1>
        <div class="row d-flex justify-content-center">
            <form class="col-6" action="{% url 'accounts:ccreate' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                {{ create_customer|crispy }}
                <!-- <input type="submit" value="Create"> -->
                <div class="row d-flex justify-content-center">
                    <div class="col-3">
                        <button type="submit" class="btn btn-success">Add Customer</button>
                    </div>
                </div>
            </form>
        </div>
        {% endblock %}
    </div>

</div>

accounts/templates/accounts/customer_detail.html
{% extends 'base-layout.html' %}
{% block content %}
<br /><br /><br />
<div class="Customer-detail">
    <h1 class="text-center text-info">Customer Detail for {{ customer.firstname }} {{ customer.lastname }}</h1>
    <table class="table table-hover table-sm table-bordered mx-auto" style="width: 1000px;">
        <tr>
            <th scope="col">ID</th>
            <td>{{ customer.c_customerid }}</td>
        </tr>
        <tr>
            <th scope="col">Name</th>
            <td>{{ customer.firstname }} {{ customer.lastname }}</td>
        </tr>
        <tr>
            <th scope="col">Company Name</th>
            <td>{{ customer.c_companyname }}</td>
        </tr>
        <tr>
            <th scope="col">Address</th>
            <td>{{ customer.c_streetaddress1 }} {{ customer.c_streetaddress2 }},
                {{ customer.c_city }} {{ customer.c_province }} - {{ customer.c_postalcode }}
                {{ customer.c_country }}</td>
        </tr>
        <tr>
            <th scope="col">Email address</th>
            <td>{{ customer.email }}</td>
        </tr>
        <tr>
            <th scope="col">Phone No.</th>
            <td>{{ customer.c_phonenumber }}</td>
        </tr>

    </table>


</div>
{% endblock %}

accounts/templates/accounts/customer_list.html
{% extends 'base-layout.html' %}

{% block content %}
<br /><br /><br />
<div class="customers">
    <h1 class="text-center text-info">Customer List</h1>
    <table class="table table-hover table-sm table-bordered mx-auto" style="width: 1000px;">
        <thead class="thead-dark">
            <tr class= "text-center">
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Company Name</th>
                <th scope="col">Address</th>
                <th scope="col">Registered on</th>
                <th scope="col">Subscribed</th>
                <th scope="col">Details</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
            <div class="customers-list">
                <tr>
                    <td>
                        <a href="{% url 'accounts:customerdetail' customerid=customer.c_customerid %}">
                            {{ customer.c_customerid }}
                        </a>
                    </td>
                    <td>{{ customer.firstname }} {{ customer.lastname }}</td>
                    <td>{{ customer.c_companyname }}</td>
                    <td>{{ customer.c_streetaddress1 }} {{ customer.c_streetaddress2 }},
                        {{ customer.c_city }} {{ customer.c_province }} - {{ customer.c_postalcode }}
                        {{ customer.c_country }}</td>
                    <td>{{ customer.c_dateregistered }}</td>
                    {% if customer.c_issubscribed %}
                    <td align="center" style="text-align:center; font-size:100%; font-weight:bold; color:green;">
                        Subscribed</td>
                    {% else %}
                    <td align="center" style="text-align:center; font-size:100%; font-weight:bold; color:red;">
                        Not Subscribed</td>
                    {% endif %}
                    <td align="center" style="text-align:center; font-size:100%; font-weight:bold; color:red;">
                        <a class="btn btn-primary"
                            href="{% url 'accounts:customerdetail' customerid=customer.c_customerid %}">
                                Detail
                        </a>
                    </td>
                </tr>
            </div>
            {% endfor %}
        </tbody>
    </table>

</div>
<br /><br /><br /><br />

{% endblock %}

accounts/templates/accounts/employee_create.html
{% extends 'base-layout.html' %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="'row">
        {% block content %}
        <br />
        <br />
        <br />
        <h1 class="text-center text-info">Add Employee</h1>
        <div class="row d-flex justify-content-center">
            <form class="col-6" action="{% url 'accounts:ecreate' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                {{ create_employee|crispy }}
                <!-- <input type="submit" value="Create"> -->
                <div class="row d-flex justify-content-center">
                    <div class="col-3">
                        <button type="submit" class="btn btn-success">Add Employee</button>
                    </div>
                </div>
            </form>
        </div>
        {% endblock %}
    </div>

</div>

accounts/templates/accounts/employee_list.html
{% extends 'base-layout.html' %}

{% block content %}<br /><br /><br />
<div class="employees">
    <h1 class="text-center text-info">Employee List</h1>
    <table class="table table-hover table-sm table-bordered mx-auto" style="width: 1000px;">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Address</th>
                <th scope="col">Joined Date</th>
                <th scope="col">Salary</th>
                <th scope="col">Job Type</th>
                
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <div class="employees-list">
                <tr>
                    <td>{{ employee.e_userid.id }}</td>
                    <td>{{ employee.firstname }} {{ employee.lastname }}</td>
                    <td>{{ employee.e_streetaddress1 }} {{ employee.e_streetaddress2 }},
                        {{ employee.e_city }} {{ employee.e_province }} - {{ employee.e_postalcode }}
                        {{ employee.e_country }}</td>
                        <td>{{ employee.e_startdate }}</td>
                        <td>$ {{ employee.formatted_salary }}</td>
                    {% if employee.e_isapprentice %}
                    <td align="center" style="text-align:center; font-size:100%; font-weight:bold; color:green;">
                        Apprentice</td>
                    {% else %}
                    <td align="center" style="text-align:center; font-size:100%; font-weight:bold; color:red;">
                        Full-Time</td>
                    {% endif %}



                </tr>
            </div>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base-layout.html' %}

{% block content %}
<!-- <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1> -->
<!-- <h1>Log in</h1> -->
<!-- <form class="site-form" action={% url 'accounts:login' %} method="post">
    {% csrf_token %}
    <table border="1">
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}

    </table>
    <input type="submit" value="Login">
</form> -->
<section class="min-vh-100 bg-light">
    <br /><br /><br />
    <br />

    <div class="container bg-grey">
        <div class="row text-white bg-secondary">
            

            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                <h2 class="display-4 py-2 text-truncate ">Please sign in</h2><br/>
                <div class="text-center"
                    style="font-size:150%; font-weight:bold; color:midnightblue; text-align:center; ">
                    {% if form.errors %}
                    <p>Your username and password didn't match. Please try again.</p>
                    {% endif %}

                    {% if next %}
                    {% if user.is_authenticated %}
                    <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                    {% else %}
                    <p>Please login to see this page.</p>
                    {% endif %}
                    {% endif %}
                </div>
                <div class="px-2">
                    <form class="form-signin" action="{% url 'accounts:login' %}" method="post" id="login-form">
                        {% csrf_token %}
                        <h2 class="form-signin-heading">{{ message }}</h2>
                        <label for="id_username" class="sr-only">Email address</label>
                        <input type="text" name="username" id="id_username" class="form-control" placeholder="User Name"
                            required autofocus><br /><br />
                        <label for="id_password" class="sr-only">Password</label>
                        <input type="password" name="password" id="id_password" class="form-control"
                            placeholder="Password" required>
                        <br /><br />
                        <button class="btn btn-lg btn-info btn-block" type="submit">Sign in</button>
                    </form>
                    {# Assumes you setup the password_reset view in your URLconf #}
                </div>
            </div>
        </div>
        <p align = "center"><a href="{% url 'password_reset' %}">Lost password?</a></p>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base-layout.html' %}

{% block content %}


<p>You are logged out!</p>
<a href="{% url 'accounts:login' %}">
    Log in again
</a>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base-layout.html' %}

{% block content %}
<h1>The password has been changed!</h1>
<p><a href="{% url 'login' %}">log in again?</a></p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base-layout.html' %}

{% block content %}
{% if validlink %}
<p>Please enter (and confirm) your new password.</p>
<form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.new_password1.errors }}
                <label for="id_new_password1">New password:</label></td>
            <td>{{ form.new_password1 }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password2.errors }}
                <label for="id_new_password2">Confirm password:</label></td>
            <td>{{ form.new_password2 }}</td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Change my password" /></td>
        </tr>
    </table>
</form>
{% else %}
<h1>Password reset failed</h1>
<p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
</p>
{% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base-layout.html' %}

{% block content %}
<p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam
    folder.</p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base-layout.html' %}

{% block content %}
<br />
<br />
<br />    
<h1 class="text-center text-info">Profile Info</h1><br />    

<table class="table table-hover table-sm mx-auto" style="width: 600px;">
    <tr style="font-size:150%; font-weight:bold; color:midnightblue;">
        <th scope="col">User Name</th>
        <td >{{ user }}</td>
    </tr>
    <tr style="font-size:150%; font-weight:bold; color:midnightblue;">
        <th >First Name</th>
        <td>{{ user.first_name }}</td>
    </tr>
    <tr style="font-size:150%; font-weight:bold; color:midnightblue;">
        <th >Last Name</th>
        <td>{{ user.last_name }}</td>
    </tr>
    <tr style="font-size:150%; font-weight:bold; color:midnightblue;">
        <th >Role</th>
        {% if user.is_staff %}
        <td>
            Cellibini Employee</td>
        {% else %}
        <td>
            Cellibini Customer</td>
        {% endif %}
    </tr>
    <tr style="font-size:150%; font-weight:bold; color:midnightblue;">
        <th>Email Address</th>
        <td>{{ user.email }}</td>
    </tr>
</table>

</div>
<br /><br /><br /><br />

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base-layout.html' %}

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    <table class="table table-hover table-sm table-bordered mx-auto" style="width: 1000px;">
         {{ form }}
     </table>
    <input type="submit" value="Sign Up">
</form>

{% endblock %}