accounts/urls.py
from django.urls import re_path, path
from . import views
from django.contrib import admin


app_name = 'accounts'

urlpatterns = [
    path('pdf/apprentices', views.Pdfapprentices.as_view()),
    # re_path(r'^signup/$', views.signup_view, name='signup'),
    re_path(r'^login/$', views.login_view, name="login"),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^profile/', views.profile, name='profile'),
    re_path(r'^password/$', views.change_password, name='change_password'),
    re_path(r'^employeecreate/$', views.employee_create, name="ecreate"),
    re_path(r'^customercreate/$', views.customer_create, name="ccreate"),
    re_path(r'^customers/$', views.customer_list, name='clist'),
    re_path(r'^employees/$', views.employee_list, name='elist'),
    re_path(r'^customerdetail/(?P<customerid>[\w-]+)$',
            views.customer_detail, name="customerdetail"),
    
]

bike/urls.py
from django.urls import re_path, path
from . import views
app_name = 'bike'
urlpatterns = [
    re_path(r'^$', views.bike_list, name="bikelist"),
    re_path(r'^bikedetail/(?P<bikeid>[\w-]+)/$',
            views.bike_detail, name="bikedetail"),
    re_path(r'^bikemodelcreate/$', views.model_create, name="mcreate"),
    re_path(r'^bikemodels/$', views.bikemodels_list, name="bikemodelslist"),
    re_path(r'^bikemodels/(?P<modelid>[\w-]+)/$',
            views.bikemodel_detail, name="bikemodeldetail"),
]

celli_webapp/urls.py
from django.contrib import admin
from django.urls import include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

# Change admin site title
admin.site.site_header = "Cellibini Bikes Company WebApp Login"
admin.site.site_title = "Cellibini Bikes Company"

app_name = 'celli_webapp'


urlpatterns = [
    # path('admin/', admin.site.urls),
    # path(r'^admin/', admin.site.urls),
    
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^taskschedule/', include('taskschedule.urls')),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^customers/', include('customers.urls')),
    re_path(r'^bike/', include('bike.urls')),
    re_path(r'^masterinventory/', include('masterInventory.urls')),
    re_path(r'^about/$', views.about),
    re_path(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customers/urls.py
from django.urls import re_path, path
from . import views

app_name = 'customers'

urlpatterns = [
    re_path(r'^$', views.customerorderlist, name='colist'),
    re_path(r'^customerorderlist/$',
            views.customerorderlist, name='colist'),
    re_path(r'^customerordercreate/$',
            views.customerordercreate, name="cocreate"),
    re_path(r'^(?P<co_customeroderid_id>[\w-]+)$',
            views.customeroderinlinecreate, name="coinlinecreate"),
    

]

masterInventory/urls.py
from django.conf.urls import url
from . import views

app_name = "masterInventory"

urlpatterns = [
	url(r'^$', views.inventory_list, name="inventorylist"),  # view all the inventory
	url(r'^inventoryorder/create$', views.inventoryorder_create, name="inventoryorder"),
	url(r'^inventoryorder/list$', views.inventoryorder_list, name="inventoryorderlist"),
	url(r'^inventoryorder/detail/(?P<orderid>[\w-]+)$', views.inventoryorder_detail, name="inventoryorderdetail"),

	url(r'^inventoryorder/approve/(?P<orderid>[\w-]+)$',views.inventoryinvoice_create, name="inventoryorderapprove"),
	#invoice routes
	url(r'^inventoryinvoice/list$', views.inventoryinvoice_list,name="inventoryinvoicelist"),
	url(r'^inventoryinvoice/detail/(?P<invoiceid>[\w-]+)$',views.inventoryinvoice_detail, name="inventoryinvoicedetail"),

	#supplier routes
	url(r'^itemcreate/$', views.inventory_item_create, name="inventoryadd"),
	url(r'^supplierlist/$', views.supplier_list, name="supplierlist"),

	#defects routes
	url(r'^defects/$', views.defects_list, name="defectslist"),
	url(r'^defects/report/(?P<invoiceid>[\w-]+)$', views.defect_create, name="defectcreate"),
	url(r'^defects/detail/(?P<defectinvoiceid>[\w-]+)/$', views.defect_detail, name="defectdetail"),
	# url(r'^defects/reportdefect$', views.create_defect, name="createdefect"),


]

taskschedule/urls.py
from django.urls import re_path, path
from . import views

app_name = 'tasks'


urlpatterns = [
    re_path(r'^$', views.task_list, name='list'),
    re_path(r'schedulelist^$', views.schedule_list, name='slist'),
    re_path(r'^create/$', views.task_create, name='create'),
    re_path(r'^createschedule/$', views.schedule_create, name='screate'),    
]

templates/about.html
{% extends 'base-layout.html' %}

{% block content %}
    This is about page
{% endblock %}

templates/base-layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab">

    <title>Cellibini Bikes Company</title>
    
</head>

<body class="bg-light">
    
    {% include 'navbar.html' %}
    
    <div class="wrapper">
            <br />
        {% block content %}
        {% endblock %}
    </div>
    <br />
    <br />
    <br />
</body>

<footer class="bg-dark text-white" style="position: fixed;left: 0;bottom: 0;width: 100%;text-align: center;">
    <p>
       Cellibini Bicycle Company Web App : 
       <span>
           Created By - Dhara Savaliya, Kevin Astilla and Sara Bhatti
       </span>
    </p>
    
</footer>
</body>

</html>
</html>

templates/homepage.html
{% extends 'base-layout.html' %}

{% block content %}
<a href="{% url 'accounts:login' %}">
<img src="/static/background.png" alt="Cellibini Bicycle Company, Created By: Dhara Savaliya, Kevins Astilla, Sara Bhatti " height="100%" width="100%" >
   </a>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'accounts:login' %}">Cellibini Bicycle Company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
            aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'tasks:list' %}" id="userMenu"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                         <form class="dropdown-item" action="{% url 'accounts:logout' %}" method="post">
                             {% csrf_token %}
                             <button class="dropdown-item" type=" submit">Logout</button>
                         </form>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Task/ Supplier List
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'tasks:list' %}">Task List</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'masterInventory:supplierlist' %}">Supplier List</a>

                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Manage Users
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'accounts:ecreate' %}">Create Employee</a>
                        <a class="dropdown-item" href="{% url 'accounts:ccreate' %}">Create Customer</a>
                        <a class="dropdown-item" href="{% url 'customers:cocreate' %}">Create Customer Order</a>

                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:elist' %}">Employee List</a>
                        <a class="dropdown-item" href="{% url 'accounts:clist' %}">Customer List</a>
                        <a class="dropdown-item" href="http://127.0.0.1:8000/admin/">Admin</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Bike Models
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'bike:bikelist'  %}">Bike List</a>
                        <a class="dropdown-item" href="{% url 'bike:bikemodelslist' %}">Bike Models List</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Master Inventory
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'masterInventory:inventorylist' %}">Inventory List</a>
                        <a class="dropdown-item" href="{% url 'masterInventory:inventoryorder' %}">Inventory Order</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'masterInventory:inventoryinvoicelist' %}">Inventory
                              Invoice List</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
            </form>
            {% endif %}
        </div>
    </div>
</nav>